import { useState } from 'react';
import { PrivacyStrip } from '../ai/PrivacyStrip';
import type { PrivacyStripData, PrivacyStripSource } from '../../types/ai';
import type { AuditObjectKind } from '../../types/audit';

// OutputReviewSource is a lightweight pin describing where a piece of
// AI output came from — the OutputReview lists these so the user can
// inspect every source before publishing or persisting.
export interface OutputReviewSource {
  id: string;
  label: string;
  excerpt?: string;
}

interface Props {
  // The AI-generated content the user is gating. Markdown is rendered
  // verbatim — the gate only formats whitespace.
  content: string;
  // Source attribution surfaced above the privacy strip.
  sources: OutputReviewSource[];
  // What kind of KApp object the content will become once accepted.
  // Used to shape the heading + Accept button copy.
  objectKind: AuditObjectKind | 'artifact-status';
  // Optional override for the heading; defaults are picked from objectKind.
  heading?: string;
  // Optional explanation rendered above the content area.
  description?: string;
  // Privacy strip data — when omitted the gate falls back to an
  // on-device, 0-byte-egress placeholder.
  privacy?: PrivacyStripData;

  onAccept: (edited: string) => void | Promise<void>;
  onEdit?: (edited: string) => void;
  onDiscard: () => void;

  // When the gate is being used to confirm a status transition (e.g.
  // draft → in_review), the parent passes the target status here so
  // the Accept button can advertise it.
  targetStatus?: string;

  // When false, the Edit button is hidden and the body is read-only.
  // Use this for confirmation flows (e.g. artifact status transitions)
  // where the parent only patches metadata and would silently drop any
  // body edits the user typed. Defaults to true so creation flows keep
  // their inline-editing affordance.
  allowEdit?: boolean;
}

const OBJECT_LABEL: Record<Props['objectKind'], string> = {
  task: 'task',
  approval: 'approval',
  artifact: 'artifact',
  form: 'form',
  'artifact-status': 'artifact status change',
};

function defaultPrivacy(): PrivacyStripData {
  return {
    computeLocation: 'on_device',
    modelName: 'bonsai-1.7b',
    sources: [],
    dataEgressBytes: 0,
    whySuggested: 'Drafted on-device from the current thread. Review before publishing.',
    origin: { kind: 'thread', id: '', label: 'Current thread' },
  };
}

// OutputReview is the human-confirmation gate (PROPOSAL.md §4.3 element
// 7 / ARCHITECTURE.md module #12). AI never writes a KApp object
// directly — every artifact / approval / task / form generated by the
// renderer's Action Launcher passes through this component first. The
// user sees the proposed content with full source attribution, can
// inline-edit it, and chooses Accept / Edit / Discard.
export function OutputReview({
  content,
  sources,
  objectKind,
  heading,
  description,
  privacy,
  onAccept,
  onEdit,
  onDiscard,
  targetStatus,
  allowEdit = true,
}: Props) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(content);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  const objectLabel = OBJECT_LABEL[objectKind];
  const computedHeading = heading
    ?? (targetStatus
      ? `Confirm ${targetStatus.replace('_', ' ')}`
      : `Review ${objectLabel} before saving`);
  const acceptLabel = targetStatus
    ? `Confirm ${targetStatus.replace('_', ' ')}`
    : `Accept ${objectLabel}`;

  const stripData = privacy ?? defaultPrivacy();
  const stripSources: PrivacyStripSource[] = sources.length
    ? sources.map((s) => ({ kind: 'message', id: s.id, label: s.label }))
    : stripData.sources;
  const strip: PrivacyStripData = { ...stripData, sources: stripSources };

  async function handleAccept() {
    setBusy(true);
    setErr(null);
    try {
      // draft is initialised to content and is the only thing the
      // textarea mutates, so it always reflects the latest text the
      // user wants to accept — including the post-"Save edits" case
      // where editing has been toggled back to false.
      await onAccept(draft);
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  }

  function handleEdit() {
    if (!editing) {
      setEditing(true);
      return;
    }
    onEdit?.(draft);
    setEditing(false);
  }

  return (
    <section
      className="output-review"
      role="dialog"
      aria-modal="false"
      aria-label={computedHeading}
      data-testid="output-review"
    >
      <header className="output-review__header">
        <h3 className="output-review__heading">{computedHeading}</h3>
        {description && <p className="output-review__description">{description}</p>}
      </header>

      {err && (
        <p className="output-review__error" role="alert">
          {err}
        </p>
      )}

      <div className="output-review__content" data-testid="output-review-content">
        {editing ? (
          <textarea
            className="output-review__editor"
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            data-testid="output-review-editor"
            rows={Math.min(20, Math.max(6, draft.split('\n').length))}
          />
        ) : (
          <pre className="output-review__body">{draft}</pre>
        )}
      </div>

      {sources.length > 0 && (
        <details className="output-review__sources" data-testid="output-review-sources">
          <summary>Sources ({sources.length})</summary>
          <ul>
            {sources.map((s) => (
              <li key={s.id} data-testid={`output-review-source-${s.id}`}>
                <strong>{s.label}</strong>
                {s.excerpt && <span className="output-review__source-excerpt"> — {s.excerpt}</span>}
              </li>
            ))}
          </ul>
        </details>
      )}

      <PrivacyStrip data={strip} />

      <footer className="output-review__actions">
        <button
          type="button"
          className="output-review__discard"
          onClick={onDiscard}
          disabled={busy}
          data-testid="output-review-discard"
        >
          Discard
        </button>
        {allowEdit && (
          <button
            type="button"
            className="output-review__edit"
            onClick={handleEdit}
            disabled={busy}
            data-testid="output-review-edit"
          >
            {editing ? 'Save edits' : 'Edit'}
          </button>
        )}
        <button
          type="button"
          className="output-review__accept"
          onClick={handleAccept}
          disabled={busy}
          data-testid="output-review-accept"
        >
          {busy ? 'Saving…' : acceptLabel}
        </button>
      </footer>
    </section>
  );
}
